### ISSUE TITLE
Running on in-the-wild images?

### ISSUE THREAD

**Issue by andrewnc** [ipl-uw/ZeDO-Release#1]
Amazing work! Thank you for your contribution and this great code. 

Do you have a minimal example of running this on an arbitrary image, for example from a web camera or cell phone?

**Comment by zhyjiang** [comment]
Hi Andrew. We have tested our method on some self-collected data, which shows the method can be easily adapted to any camera with known camera parameters.

We plan to release the in-the-wild inference code after our paper is accepted. If you want to try the method now, you can easily modify the code and build your custom dataset.

**Comment by davidea97** [comment]
Outstanding work!
May I ask if there is a specific schedule for in-the-wild inference code release? Thanks, I am looking forward to it.

**Comment by zhyjiang** [comment]
We just released the inference code for custom datasets~
