### ISSUE TITLE
Preparation of SyRIP Data for Inference

### ISSUE THREAD

**Issue by diegosancarmen** [ipl-uw/ZeDO-Release#2]
Hello! 

In `syrip_process.py` , line 6:
```
name_map = np.load('./data/survey_data/img_name700_map.npy')
```
this `.npy` file is not included in the repo or in the ZeDO-Infant [drive folder](https://drive.google.com/drive/u/0/folders/1rgeVMuMVkf7IUERdSlSNgBF01jRLx-xb). Wanted to reach out and inquire if this file could be made available for processing the SyRIP data for evaluation.

Thank you!

**Comment by xcharxlie** [comment]
Hi!
The file is actually from the official SYRIP dataset. Please check the readme file which mentions how to download it https://github.com/ostadabbas/Infant-Postural-Symmetry/
